CodeTrophs/MarchCode

Day 1/narayan.cpp
Day 1 added code for finding odd even numbers
=> new file narayan.cpp added

Day 1/KASHYAPMOHIT921.c
`#include <stdio.h>
#include <stdlib.h>
int main()
{ int  num;
printf("ENTER THE NUMBER:");
scanf("%d",&num);
if(num%2==0)
printf("\nGIVEN NUMBER IS EVEN");
else
printf("\nGIVEN NUMBER IS ODD");
return 0;
}`
=> ODDEVENCODE

Day 1/.ipynb_checkpoints/1218muskan-checkpoint.ipynb, Day 1/1218muskan.cpp, Day 1/1218muskan.ipynb
day 1 contribution in c++ and python
=> Day 1 contribution

Odd_Even
- Rename code file name <USERNAME.cpp or .java or .py> and Upload Day 1 Folder .
- Don't push to main branch . Create new branch use this command line git checkout -b <username>  ( Example git checkout -b aryasoni98 )
=> Day 1 : Odd_Even

main.cpp
- Rename code file name <USERNAME.cpp or .java or .py> and Upload Day 1 Folder .
- Don't push to main branch . Create new branch use this command line git checkout -b ( Example git checkout -b aryasoni98 )
=> Question 1

DIVISIBLE.cbp
`#include <stdio.h>
#include <stdlib.h>
int main()
{int num;
printf("ENTER THE NUMBER:" );
scanf("%d",&num);
if(num%11==0)
if(num%5==0)
printf("\nGIVEN NUMBER IS DIVISIBLE BY BOTH 5 AND 11");
else
printf("\nCONDITION FAILED");
return 0;
}
`
=> day 2 code in C

Day 3/CoreTeam/Nandini7637.java
=> nandini7637 added day 3 solution

Day 1/MelasMalephar.cpp, Day 2/MelasMalephar.cpp, Day 3/MelasMalephar.cpp, Day 4/MelasMalephar .CPP
Even Odd No finder
Divisible test
Day Finder
(Sorry for the Delay)
=> MelasMalephar Day 1 Contribution

Day 4/CodeTeam/nandini7637.java
=> nandini7637 added day4 solution

Day 4/AsciiCode.cpp
=> Day-4 ASCII code of number

ascii.c
`#include <stdio.h>
#include <stdlib.h>
int main()
{int m,n;
printf("UPPER RANGE=");
scanf("%d",&m);
printf("\nLOWER RANGE=");
scanf("%d",&n);
if(n*m>0&&m>n)
for(int i=n;i<=m;i++)
printf("%d ",i);
else
printf("WRONG DATA ENTERED");
return 0;
}
`
=> day 5 code in c

Day 5/CoreTeam/nandini7637.java
=> nandini7637 added day5 solution

Day 5/hasan8130.java
print natural number for a given range
=> Day 5 contribution

day6.py
Solved this question "Write a program to print the sum of all the numbers and also the sum of all the even numbers between ( n and m )" using python
=> Day 6 in python

Day 6/.ipynb_checkpoints/Untitled-checkpoint.ipynb, Day 6/1218muskan.cpp, Day 6/Untitled.ipynb
Day 6 contribution in c++ and python
=> Day 6 contribution

Day 6/CoreTeam/nandini7637.java
=> nandini7637 added day6 solution

day7.py
soled this question "To count the number of digits in a number." using python.
=> Day 7 in python

Day 7/Core Team/nandini7637.java
=> nandini7637 added day7 solution

day8.py
Solved this question 'To find the factorial of a given number.' using python.
=> Day 8 in Python

Day 8/.ipynb_checkpoints/1218muskan-checkpoint.ipynb, Day 8/1218muskan.cpp, Day 8/1218muskan.ipynb
Day 8 contribution in c++ and python
=> Day 8 contribution

day9.py
Solved this question "To find the sum of the first digit and the last digit of a given number ." using python.
=> Day 9 in Python

Day 9/.ipynb_checkpoints/1218muskan-checkpoint.ipynb, Day 9/1218muskan.cpp, Day 9/1218muskan.ipynb
Day 9 contribution in c++ and python
=> Day 9 contribution

Day 9/Core Team/nandini7637.java
=> nandini7637 added day9 solution

day10.py
Solved this question "To find HCF of two numbers" using python.
=> Day 10 in Python

Day 10/1218muskan.cpp, Day 10/1218muskan.ipynb
Day 10 contribution in c++ and python
=> Day 10 contribution

Day 10/nandini7637.java
=> nandini7637 added day 10 solution

Day 11/.ipynb_checkpoints/1218muskan-checkpoint.ipynb, Day 11/1218muskan.cpp, Day 11/1218muskan.ipynb
Day 11 contribution in c++ and python
=> Day 11 contribution

day11.py
Solved this question "To find LCM of two numbers" using python
=> Day 11 in Python

Day 11/Core Team/nandini7637.java
=> added day 11 solution

day12.py
Solved this question "To find all the prime numbers between ( n and m )" using python
=> Day 12 in Python

Day 12/nandini7637.java
=> nandini7637 added day12 solution

Day 13/nandini7637.java
=> nandini7637 added day 13 solution

day13.py
Solved this question "To find whether a number is Armstrong or not." using python
=> Day 13 in Python

day14.py
Solved this question " To find whether a number is Perfect or not." using Python.
=> Day 14 in Python

Day 14/.ipynb_checkpoints/1218muskan-checkpoint.ipynb, Day 14/1218muskan.cpp, Day 14/1218muskan.ipynb
Day 14 contribution in c++ and python
=> Day 14 contribution

day15.py
Solved this question " To find whether a number is Strong or not." using Python.
=> Day 15 in Python

Day 15/.ipynb_checkpoints/1218muskan-checkpoint.ipynb, Day 15/1218muskan.cpp, Day 15/1218muskan.ipynb
Day 15 contribution in c++ and python
=> Day 15 contribution

day16.py
Solved this question "To check Whether a number is palindrome or not" using python.
=> Day 16 in Python

Day 16/.ipynb_checkpoints/1218muskan-checkpoint.ipynb, Day 16/1218muskan.cpp, Day 16/1218muskan.ipynb
Day 16 contribution in c++ and python
=> Day 16 contribution

day17.py
Solved this question "To print n number of fibonacci series." using Python.
=> Day 17 in Python

Day 17/.ipynb_checkpoints/1218muskan-checkpoint.ipynb, Day 17/1218muskan.cpp, Day 17/1218muskan.ipynb
Day 17 contribution in c++ and python
=> Day 17 contribution

Day 17/nandini7637.java
=> day17 solution by nandini7637

Day 18/.ipynb_checkpoints/1218muskan-checkpoint.ipynb, Day 18/1218muskan.cpp, Day 18/1218muskan.ipynb
Day 18 contribution in python and c++
=> Day 18 contribution

Day 17/Core Team/python.py, day19.py
Solved this question " To print a the lower triangle matrix. " using python.
=> Day 19 in Python

Day 19/.ipynb_checkpoints/1218muskan-checkpoint.ipynb, Day 19/1218muskan.cpp, Day 19/1218muskan.ipynb
Day 19 contribution in c++ and python
=> Day 19 contribution

README.md
updated readme file with contributors section which will show contributors of this project
=> updated readme with contributors section

Day 20/1218muskan.cpp, Day 20/1218muskan.ipynb
Day 20 contribution in c++ and python
=> Day 20 contribution

day20.py
Solved this question "Write a program to print the pattern upto n number" using python.
=> Day 20 in python

Day 20/nandini7637.java
=> nandini7637 added day 20 solution

Day 21/1218muskan.cpp, Day 21/1218muskan.ipynb
Day 21 contribution in c++ and python
=> Day 21 contribution

Day 18/Core Team/main (1).py, Day 20/Core Team/python.py, day22.py
Solved this question "To Find the maximum and minimum number in an array" using python
=> Day 22 in Python

Day 23/1218muskan.cpp, Day 23/1218muskan.ipynb
Day 23 contribution in C++ and python
=> Day 23 contribution

day23.py
Solved this question "To count the total number of odd and even numbers in array" using python.
=> Day 23 in python

Day 24/1218muskan.cpp, Day 24/1218muskan.ipynb
Day 24 contribution in C++ and python
=> Day 24 contribution

day24.py
Solved this question "To print all the unique elements in an array." using python.
=> Day 24 in python

Day 25/1218muskan.cpp, Day 25/1218muskan.ipynb
Day 25 contribution in C++ and python
=> Day 25 contribution

Day 26/1218muskan.cpp, Day 26/1218muskan.ipynb
Day 26 contribution in python and C++
=> Day 26 contribution

Day 27/1218muskan.cpp, Day 27/1218muskan.ipynb
Day 27 contribution in python and C++
=> Day 27 contribution

Day 22/Core Team/Python.py, day27.py
Solved this question "WAP using a function to find the factorial of a number using recursion" using python.
=> Day 27 in python

Day 26/nandini7637.java
=> nandini7637 added day 26 solution

Day 29/1218muskan.cpp, Day 29/1218muskan.ipynb
Day 29 contribution in Python and c++
=> Day 29 contribution

day29.py
Solved this question "WAP using the function to take a string as input and find the number of words in it." using python.
=> Day 29 in python

Day 30/.ipynb_checkpoints/1218muskan-checkpoint.ipynb, Day 30/1218muskan.ipynb
=> Day 30 contribution
